/**
 * Auto-generated by scripts/generate-version.js — do not edit.
 *
 * Baked into the bundle at build time. The client compares this against
 * /version.json (which is fetched fresh from the server) to detect when a
 * newer build has been deployed.
 */
export const BUILD_VERSION = "32e8493-mpzc20z0"
export const BUILD_COMMIT  = "32e8493"
export const BUILT_AT      = "2026-06-04T10:08:54.636Z"
