/**
 * Auto-generated by scripts/generate-version.js — do not edit.
 *
 * Baked into the bundle at build time. The client compares this against
 * /version.json (which is fetched fresh from the server) to detect when a
 * newer build has been deployed.
 */
export const BUILD_VERSION = "7550dc4-mqcek1rf"
export const BUILD_COMMIT  = "7550dc4"
export const BUILT_AT      = "2026-06-13T13:39:54.987Z"
