/**
 * Auto-generated by scripts/generate-version.js — do not edit.
 *
 * Baked into the bundle at build time. The client compares this against
 * /version.json (which is fetched fresh from the server) to detect when a
 * newer build has been deployed.
 */
export const BUILD_VERSION = "9b958c1-mpvclz11"
export const BUILD_COMMIT  = "9b958c1"
export const BUILT_AT      = "2026-06-01T15:13:20.533Z"
