#!/usr/bin/env node
/**
 * Build-time version stamp.
 *
 * Runs as part of `npm run build` (via the prebuild script in package.json).
 * Writes:
 *   - public/version.json  (served as /version.json — polled by the client)
 *   - lib/build-info.ts    (imported by app code at build time, baked into bundle)
 *
 * Both contain { version, commit, builtAt } so the client can compare what
 * was bundled vs. what's currently deployed and prompt a refresh on mismatch.
 */

const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

function safe(cmd, fallback = '') {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
  } catch {
    return fallback
  }
}

const commit = safe('git rev-parse --short HEAD', 'unknown')
const builtAt = new Date().toISOString()
// Combine commit + millis so same commit re-builds also bump the version.
const version = `${commit}-${Date.now().toString(36)}`

const payload = { version, commit, builtAt }

const root = path.resolve(__dirname, '..')
const publicPath = path.join(root, 'public', 'version.json')
const libPath = path.join(root, 'lib', 'build-info.ts')

fs.writeFileSync(publicPath, JSON.stringify(payload, null, 2) + '\n')

const libContent = `/**
 * Auto-generated by scripts/generate-version.js — do not edit.
 *
 * Baked into the bundle at build time. The client compares this against
 * /version.json (which is fetched fresh from the server) to detect when a
 * newer build has been deployed.
 */
export const BUILD_VERSION = ${JSON.stringify(version)}
export const BUILD_COMMIT  = ${JSON.stringify(commit)}
export const BUILT_AT      = ${JSON.stringify(builtAt)}
`
fs.writeFileSync(libPath, libContent)

console.log(`[version] ${version}  ·  commit ${commit}  ·  ${builtAt}`)
